remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme 

title: " " 
logo: /assets/img/logo.png
description: Open-Source Photonic Simulation & Optimization
github:
  is_project_page: false
  is_user_page: false
  show_downloads: false
  owner: spinsphotonics
